from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]

def replace_once(rel,old,new):
    p=ROOT/rel
    s=p.read_text()
    n=s.count(old)
    if n!=1:
        raise RuntimeError(f'{rel}: expected one replacement, got {n}: {old[:140]!r}')
    p.write_text(s.replace(old,new,1))

# Replace the first external-count approximation with a mixed future-boundary
# projection. The rapid planner stays the sole compressed global-count owner,
# but it can see one already-owned charge suffix actor's future shot times.
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''        "_squad_ammo_dispatched_count", "_squad_ammo_external_count",\n        "_squad_ammo_external_actors", "_moris_frame_observed_actors",\n        "_event_count_getter",\n''',
    '''        "_squad_ammo_dispatched_count", "_squad_ammo_external_actor",\n        "_squad_ammo_external_count_getter", "_squad_ammo_external_shots_getter",\n        "_squad_ammo_external_expected", "_moris_frame_observed_actors",\n        "_event_count_getter",\n''',
)
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''        self._squad_ammo_dispatched_count = 0\n        self._squad_ammo_external_count = 0\n        self._squad_ammo_external_actors: frozenset[int] = frozenset()\n        self._moris_frame_observed_actors: set[int] = set()\n''',
    '''        self._squad_ammo_dispatched_count = 0\n        self._squad_ammo_external_actor: int | None = None\n        self._squad_ammo_external_count_getter: Callable[[], int] | None = None\n        self._squad_ammo_external_shots_getter: Callable[[], tuple[tuple[float, int], ...]] | None = None\n        self._squad_ammo_external_expected: tuple[float, int, int] | None = None\n        self._moris_frame_observed_actors: set[int] = set()\n''',
)
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''    def attach_squad_ammo_thresholds(\n        self,\n        thresholds: tuple[int, ...],\n        *,\n        external_actors: tuple[int, ...] | frozenset[int] = (),\n    ) -> None:\n        if self._states:\n            raise RuntimeError("Fast squad-ammo thresholds must be attached before weapon start")\n        values=tuple(sorted({int(value) for value in thresholds if int(value)>0}))\n        external=frozenset(int(actor) for actor in external_actors)\n        all_actors=set(range(len(self.squad.members)))\n        if values and (set(self.actors) | set(external)) != all_actors:\n            raise NotImplementedError("Fast squad-ammo requires every actor on an owned cadence runtime")\n        if set(self.actors) & set(external):\n            raise ValueError("Fast squad-ammo external actors overlap rapid runtime")\n        self._squad_ammo_thresholds=values\n        self._squad_ammo_external_actors=external\n''',
    '''    def attach_squad_ammo_thresholds(\n        self,\n        thresholds: tuple[int, ...],\n        *,\n        external_actor: int | None = None,\n        external_count_getter: Callable[[], int] | None = None,\n        external_shots_getter: Callable[[], tuple[tuple[float, int], ...]] | None = None,\n    ) -> None:\n        if self._states:\n            raise RuntimeError("Fast squad-ammo thresholds must be attached before weapon start")\n        values=tuple(sorted({int(value) for value in thresholds if int(value)>0}))\n        all_actors=set(range(len(self.squad.members)))\n        external=set() if external_actor is None else {int(external_actor)}\n        if values and (set(self.actors) | external) != all_actors:\n            raise NotImplementedError("Fast squad-ammo requires every actor on an owned cadence runtime")\n        if set(self.actors) & external:\n            raise ValueError("Fast squad-ammo external actor overlaps rapid runtime")\n        if external and (external_count_getter is None or external_shots_getter is None):\n            raise ValueError("Fast mixed squad-ammo requires charge count and future-shot getters")\n        self._squad_ammo_thresholds=values\n        self._squad_ammo_external_actor=None if external_actor is None else int(external_actor)\n        self._squad_ammo_external_count_getter=external_count_getter\n        self._squad_ammo_external_shots_getter=external_shots_getter\n''',
)
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''    def _predict_next_squad_ammo_boundary(self) -> tuple[float, int, int, int] | None:\n        if not self._squad_ammo_thresholds or not self.actors:\n            return None\n        probes={actor: replace(self._states[actor]) for actor in self.actors}\n        current=sum(st.hit_count for st in probes.values()) + self._squad_ammo_external_count\n        target=self._next_squad_ammo_target(current)\n        if target is None:\n            return None\n        while current < target:\n            candidates=[]\n            for actor,st in probes.items():\n                when=self._probe_next_physical_shot(st)\n                if when is not None:\n                    candidates.append((when,actor))\n            if not candidates:\n                return None\n            when,actor=min(candidates)\n            if when > self.duration + _EPS:\n                return None\n            st=probes[actor]\n            self._after_shot(st,when)\n            current += 1\n            if current == target:\n                return when,actor,st.hit_count,target\n        return None\n''',
    '''    def _current_squad_ammo_count(self) -> int:\n        external=(\n            int(self._squad_ammo_external_count_getter())\n            if self._squad_ammo_external_count_getter is not None\n            else 0\n        )\n        return sum(st.hit_count for st in self._states.values()) + external\n\n    def _predict_next_squad_ammo_boundary(\n        self,\n    ) -> tuple[float, int, int, int, bool] | None:\n        if not self._squad_ammo_thresholds or not self.actors:\n            return None\n        probes={actor: replace(self._states[actor]) for actor in self.actors}\n        external_rows=(\n            tuple(self._squad_ammo_external_shots_getter())\n            if self._squad_ammo_external_shots_getter is not None\n            else ()\n        )\n        external_index=0\n        current=(\n            sum(st.hit_count for st in probes.values())\n            + (\n                int(self._squad_ammo_external_count_getter())\n                if self._squad_ammo_external_count_getter is not None\n                else 0\n            )\n        )\n        target=self._next_squad_ammo_target(current)\n        if target is None:\n            return None\n        while current < target:\n            candidates=[]\n            for actor,st in probes.items():\n                when=self._probe_next_physical_shot(st)\n                if when is not None:\n                    candidates.append((when,actor,False))\n            if external_index < len(external_rows):\n                when,actor=external_rows[external_index]\n                candidates.append((float(when),int(actor),True))\n            if not candidates:\n                return None\n            when,actor,is_external=min(candidates,key=lambda row:(row[0],row[1]))\n            if when > self.duration + _EPS:\n                return None\n            expected=0\n            if is_external:\n                external_index += 1\n            else:\n                st=probes[actor]\n                self._after_shot(st,when)\n                expected=st.hit_count\n            current += 1\n            if current == target:\n                return when,actor,expected,target,is_external\n        return None\n''',
)
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''        when,actor,expected,target=row\n        when=max(float(now),float(when))\n        if when > self.duration + _EPS:\n            return\n        increment=target-self._squad_ammo_dispatched_count\n        if increment <= 0:\n            return\n        self._squad_ammo_scheduled_time=when\n        self.scheduler.schedule(\n            when,EventKind.PRE_SHOT_BOUNDARY,actor=actor,\n            payload=DynamicSquadAmmoToken(\n                self._squad_ammo_generation,actor,expected,target,increment\n            ),\n        )\n''',
    '''        when,actor,expected,target,is_external=row\n        when=max(float(now),float(when))\n        if when > self.duration + _EPS:\n            return\n        increment=target-self._squad_ammo_dispatched_count\n        if increment <= 0:\n            return\n        self._squad_ammo_scheduled_time=when\n        if is_external:\n            self._squad_ammo_external_expected=(when,actor,target)\n            return\n        self._squad_ammo_external_expected=None\n        self.scheduler.schedule(\n            when,EventKind.PRE_SHOT_BOUNDARY,actor=actor,\n            payload=DynamicSquadAmmoToken(\n                self._squad_ammo_generation,actor,expected,target,increment\n            ),\n        )\n''',
)
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''    def refresh_squad_ammo_plan(self, now: float) -> None:\n        if not self._squad_ammo_thresholds:\n            return\n        self._squad_ammo_generation += 1\n        self._squad_ammo_scheduled_time=None\n        self._plan_squad_ammo(now)\n\n    def record_external_squad_ammo(self, actor: int, now: float) -> int | None:\n        """Record one already-scored external physical shot.\n\n        Charge shots are sparse boundaries in the composite runtime. They do not\n        need to be predicted by the rapid probe: every observed external shot\n        advances the real global count and invalidates/replans the conservative\n        rapid-only future threshold. The returned increment is emitted only when\n        this exact charge shot crosses a compressed global threshold.\n        """\n        actor=int(actor)\n        if actor not in self._squad_ammo_external_actors:\n            raise ValueError("Fast squad-ammo external actor is not registered")\n        before=(\n            sum(st.hit_count for st in self._states.values())\n            + self._squad_ammo_external_count\n        )\n        target=self._next_squad_ammo_target(before)\n        self._squad_ammo_external_count += 1\n        after=before + 1\n        increment=None\n        if target is not None and after == target:\n            increment=target-self._squad_ammo_dispatched_count\n            if increment <= 0:\n                raise RuntimeError("Fast squad-ammo external crossing did not advance dispatched phase")\n            self._squad_ammo_dispatched_count=target\n        self.refresh_squad_ammo_plan(float(now))\n        return increment\n\n''',
    '''    def refresh_squad_ammo_plan(self, now: float) -> None:\n        if not self._squad_ammo_thresholds:\n            return\n        self._squad_ammo_generation += 1\n        self._squad_ammo_scheduled_time=None\n        self._squad_ammo_external_expected=None\n        self._plan_squad_ammo(now)\n\n    def record_external_squad_ammo(self, actor: int, now: float) -> int | None:\n        """Observe one already-scored charge shot and dispatch a planned crossing."""\n        actor=int(actor)\n        if actor != self._squad_ammo_external_actor:\n            raise ValueError("Fast squad-ammo external actor is not registered")\n        after=self._current_squad_ammo_count()\n        before=after-1\n        target=self._next_squad_ammo_target(before)\n        increment=None\n        if target is not None and after == target:\n            expected=self._squad_ammo_external_expected\n            if (\n                expected is None\n                or abs(expected[0]-float(now)) > 1e-7\n                or expected[1] != actor\n                or expected[2] != target\n            ):\n                raise RuntimeError("Fast mixed squad-ammo charge crossing was not pre-proved")\n            increment=target-self._squad_ammo_dispatched_count\n            if increment <= 0:\n                raise RuntimeError("Fast squad-ammo external crossing did not advance dispatched phase")\n            self._squad_ammo_dispatched_count=target\n        self.refresh_squad_ammo_plan(float(now))\n        return increment\n\n''',
)
replace_once(
    'fast_engine/engine/dynamic_rapid.py',
    '''        before=(\n            sum(state.hit_count for state in self._states.values())\n            + self._squad_ammo_external_count\n        )\n''',
    '''        before=self._current_squad_ammo_count()\n''',
)

# Composite charge runtime supplies the one suffix actor's current count and a
# copy-only future physical-shot projection. This reuses the existing charge
# state machine and is invalidated by the same sparse runtime sync boundaries.
replace_once(
    'fast_engine/engine/dynamic_weapon.py',
    'from dataclasses import dataclass\n',
    'from dataclasses import dataclass, replace\n',
)
replace_once(
    'fast_engine/engine/dynamic_weapon.py',
    '''    def attach_squad_ammo_thresholds(self, thresholds: tuple[int, ...]) -> None:\n        rapid=set(self._rapid_reload.actors)\n        external=frozenset(set(range(len(self.squad.members))) - rapid)\n        if external:\n            if any(\n                actor not in self._score_actors\n                or str(self.squad.members[actor].weapon.get("fire_mode") or "") != "charge"\n                for actor in external\n            ):\n                raise NotImplementedError("Fast mixed squad-ammo external actor is not an owned charge scorer")\n            if rapid and max(rapid) >= min(external):\n                raise NotImplementedError("Fast mixed squad-ammo first slice requires charge actors after rapid actors")\n        self._squad_ammo_charge_actors=external\n        self._rapid_reload.attach_squad_ammo_thresholds(\n            thresholds, external_actors=external\n        )\n''',
    '''    def _predict_squad_ammo_charge_shots(\n        self, actor: int\n    ) -> tuple[tuple[float, int], ...]:\n        source=self._states.get(int(actor))\n        if source is None:\n            return ()\n        st=replace(source)\n        out=[]\n        while st.phase_end <= self.duration + 1e-9:\n            when=float(st.phase_end)\n            if st.phase == "charging":\n                if self._latch_charge_until_release(st,when):\n                    continue\n                out.append((when,int(actor)))\n                self._after_shot(st,when)\n                continue\n            self._finish_nonshot_phase(st,when,when)\n        return tuple(out)\n\n    def attach_squad_ammo_thresholds(self, thresholds: tuple[int, ...]) -> None:\n        rapid=set(self._rapid_reload.actors)\n        external=sorted(set(range(len(self.squad.members))) - rapid)\n        if not external:\n            self._squad_ammo_charge_actors=frozenset()\n            self._rapid_reload.attach_squad_ammo_thresholds(thresholds)\n            return\n        if len(external) != 1:\n            raise NotImplementedError("Fast mixed squad-ammo first slice requires exactly one charge actor")\n        actor=external[0]\n        if (\n            actor not in self._score_actors\n            or str(self.squad.members[actor].weapon.get("fire_mode") or "") != "charge"\n            or actor != len(self.squad.members)-1\n            or (rapid and max(rapid) >= actor)\n        ):\n            raise NotImplementedError("Fast mixed squad-ammo requires one owned final charge actor")\n        self._squad_ammo_charge_actors=frozenset({actor})\n        self._rapid_reload.attach_squad_ammo_thresholds(\n            thresholds,\n            external_actor=actor,\n            external_count_getter=lambda actor=actor: self._states[actor].full_charge_count,\n            external_shots_getter=lambda actor=actor: self._predict_squad_ammo_charge_shots(actor),\n        )\n''',
)

# Tighten the score proof to the exact first mixed shape: one ordinary safe
# charge actor, and it is the final roster actor. Neon/Velvet remains closed.
replace_once(
    'fast_engine/engine/score.py',
    '''        if not base_rapid or not base_charge:\n            return False\n        if rapid_runtime != base_rapid or (base_rapid | base_charge) != all_actors:\n            return False\n        if max(base_rapid) >= min(base_charge):\n            return False\n''',
    '''        if not base_rapid or len(base_charge) != 1:\n            return False\n        charge_actor=next(iter(base_charge))\n        if rapid_runtime != base_rapid or (base_rapid | base_charge) != all_actors:\n            return False\n        if charge_actor != len(squad.members)-1 or max(base_rapid) >= charge_actor:\n            return False\n''',
)

print('mixed squad-ammo threshold ownership fix applied')
