from pathlib import Path

p = Path("fast_engine/tests/test_dynamic_weapon_change.py")
text = p.read_text(encoding="utf-8")
old = '''    def test_red_hood_mint_frika_team_is_score_certified(self):\n        squad, compiled = self._team("레이드_레드후드퀀시")\n        self.assertEqual(static_score_blockers(compiled), ())\n        cfg = spec.build_config(squad, {\n            "duration": 30.0,\n            "first_burst_time": 3.0,\n            "rng_mode": "expected",\n        })\n        policy = compile_burst_policy(squad, compiled, cfg)\n        score = score_static_squad(\n            compiled,\n            policy,\n            EnemyStaticProfile(defense=31784.0, duration=30.0),\n        )\n        self.assertGreater(score.squad_total, 0.0)\n        self.assertEqual(score.unsupported, ())\n'''
new = '''    def test_red_hood_mint_frika_team_clears_weapon_change_and_max_ammo_blockers(self):\n        squad, compiled = self._team("레이드_레드후드퀀시")\n        self.assertEqual(static_score_blockers(compiled), ())\n        cfg = spec.build_config(squad, {\n            "duration": 30.0,\n            "first_burst_time": 3.0,\n            "rng_mode": "expected",\n        })\n        policy = compile_burst_policy(squad, compiled, cfg)\n        score = score_static_squad(\n            compiled,\n            policy,\n            EnemyStaticProfile(defense=31784.0, duration=30.0),\n        )\n        self.assertGreater(score.squad_total, 0.0)\n        self.assertTrue(score.unsupported)\n        self.assertTrue(all(item.startswith("skill_damage:라피 : 레드 후드:") for item in score.unsupported))\n        self.assertFalse(any("weapon_change" in item or "max_ammo" in item for item in score.unsupported))\n'''
if old not in text:
    raise SystemExit("focused test anchor not found")
text = text.replace(old, new, 1)

# Add a direct state/view regression so this slice is validated independently of
# Rapi: Red Hood's unrelated unsupported skill-damage effects in the public team.
anchor = '''    def test_red_hood_transform_shape_is_narrow(self):\n'''
insert = '''    def test_red_hood_transform_activates_and_restores_effective_weapon(self):\n        from fast_engine.engine.burst import BurstPolicy, BurstSignal\n        from fast_engine.engine.burst_runtime import BurstRuntime\n\n        _squad, compiled = self._team("레이드_레드후드퀀시")\n        actor = next(i for i, member in enumerate(compiled.members) if member.name == "레드 후드")\n        runtime = BurstRuntime(\n            compiled,\n            BurstPolicy(duration=20.0, first_burst_time=3.0),\n            EnemyStaticProfile(defense=31784.0, duration=20.0),\n        )\n        runtime.weapons.start(0.0)\n        base = runtime.weapons.effective_weapon(actor, 0.0)\n        self.assertEqual(base["max_ammo"], compiled.members[actor].weapon["max_ammo"])\n\n        runtime.dispatcher.dispatch(BurstSignal(1.0, "squad_burst_cast:3", actor, actor))\n        runtime.weapons.sync(1.0)\n        changed = runtime.weapons.effective_weapon(actor, 1.0)\n        self.assertEqual(changed["weapon_type"], "SR")\n        self.assertEqual(changed["damage_coeff"], 51.46)\n        self.assertEqual(changed["max_ammo"], -1)\n        self.assertEqual(changed["full_charge_mult"], 250)\n        self.assertEqual(changed["post_fire_delay"], 0.3)\n        self.assertEqual(runtime.weapons._full_ammo(actor, 1.0), 999999)\n\n        expiry = None\n        while runtime.scheduler:\n            event = runtime.scheduler.pop()\n            if abs(event.time - 11.0) < 1e-9:\n                expiry = event\n                break\n        self.assertIsNotNone(expiry)\n        runtime.dispatcher.handle_expiry(expiry)\n        runtime.weapons.sync(11.0)\n        restored = runtime.weapons.effective_weapon(actor, 11.0)\n        self.assertIs(restored, compiled.members[actor].weapon)\n\n'''
if anchor not in text:
    raise SystemExit("insert anchor not found")
text = text.replace(anchor, insert + anchor, 1)
p.write_text(text, encoding="utf-8")
